import React, { useState, useEffect } from 'react'
import { API_BASE_URL } from './config'
import { useForm, ValidationError } from '@formspree/react'
import Header from './components/Header'
import MainContent from './components/MainContent'
import HealthTips from './components/HealthTips'
import Footer from './components/Footer'
import BackgroundMap from './components/BackgroundMap'
import MapOverlay from './components/MapOverlay'
import 'leaflet/dist/leaflet.css'
import './index.css'

function PrivacyPolicy() {
  return (
    <div className="p-8 md:p-12 max-w-4xl mx-auto mt-8 bg-slate-900/60 backdrop-blur-3xl border border-emerald-500/20 rounded-[2rem] shadow-[0_0_50px_-12px_rgba(16,185,129,0.2)] pointer-events-auto">
      <div className="flex items-center gap-4 mb-8 border-b border-white/10 pb-6">
        <div className="p-3 bg-emerald-500/20 rounded-2xl border border-emerald-500/30 text-emerald-400">
          <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" /></svg>
        </div>
        <div>
          <h2 className="text-3xl font-black text-white tracking-tight">Data Privacy</h2>
          <p className="text-emerald-400 font-semibold text-sm mt-1 uppercase tracking-widest">A Machine Learning Based Predictive Model</p>
        </div>
      </div>
      <div className="space-y-6 text-slate-300 font-medium leading-relaxed text-lg">
        <p className="p-4 bg-white/5 rounded-2xl border border-white/5">At AirGuard, we take your privacy seriously. The location data and environmental metrics we collect are anonymized and used solely for training our predictive models to forecast next-day air emissions and enable early community health interventions.</p>
        <p className="p-4 bg-white/5 rounded-2xl border border-white/5">Your exact geographical coordinates are never shared with third parties. AirGuard's machine learning backend processes all information locally to generate region-specific health tips without compromising individual privacy.</p>
      </div>
    </div>
  )
}

function TermsOfService() {
  return (
    <div className="p-8 md:p-12 max-w-4xl mx-auto mt-8 bg-slate-900/60 backdrop-blur-3xl border border-emerald-500/20 rounded-[2rem] shadow-[0_0_50px_-12px_rgba(16,185,129,0.2)] pointer-events-auto">
      <div className="flex items-center gap-4 mb-8 border-b border-white/10 pb-6">
        <div className="p-3 bg-amber-500/20 rounded-2xl border border-amber-500/30 text-amber-400">
          <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" /></svg>
        </div>
        <div>
          <h2 className="text-3xl font-black text-white tracking-tight">Terms of Service</h2>
          <p className="text-amber-400 font-semibold text-sm mt-1 uppercase tracking-widest">Liability & Usage Agreement</p>
        </div>
      </div>
      <div className="space-y-6 text-slate-300 font-medium leading-relaxed text-lg">
        <p className="p-4 bg-white/5 rounded-2xl border border-white/5">The predictions and health directives provided by AirGuard are generated by machine learning algorithms (Multi-Output HistGradientBoostingRegressor). These are provided for informational purposes only and do not constitute professional medical advice.</p>
        <p className="p-4 bg-white/5 rounded-2xl border border-white/5 text-amber-200/80">By using our predictive model for forecasting next-day air emissions, you agree that we are not liable for any health incidents. Always consult a physician for serious medical conditions relating to air quality exposure.</p>
      </div>
    </div>
  )
}

function ContactExpert() {
  const [state, handleSubmit] = useForm("mykrdgda");
  
  if (state.succeeded) {
      return (
        <div className="p-8 md:p-12 max-w-xl mx-auto mt-12 bg-emerald-900/60 backdrop-blur-3xl border border-emerald-500/40 rounded-[2rem] shadow-[0_0_60px_-15px_rgba(16,185,129,0.4)] pointer-events-auto text-center transform hover:scale-105 transition-transform duration-500">
          <div className="w-20 h-20 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
            <svg className="w-10 h-10 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" /></svg>
          </div>
          <h2 className="text-3xl font-black text-white mb-3">Transmission Successful</h2>
          <p className="text-emerald-200/80 text-lg font-medium">Thanks for reaching out! Our ML scientists and environmental experts will review your inquiry and respond shortly.</p>
        </div>
      );
  }

  return (
    <div className="p-8 md:p-12 max-w-xl mx-auto mt-12 bg-slate-900/60 backdrop-blur-3xl border border-emerald-500/20 rounded-[2rem] shadow-[0_0_50px_-12px_rgba(16,185,129,0.2)] pointer-events-auto">
      <div className="text-center mb-8">
        <h2 className="text-3xl font-black text-white mb-2">Contact an Expert</h2>
        <p className="text-emerald-400 text-sm font-semibold uppercase tracking-widest mb-2">Connect with our AI Research Team</p>
        <p className="text-slate-400 text-sm font-medium">Discuss our machine learning based predictive model for forecasting next-day air emissions.</p>
      </div>
      
      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="group">
          <label htmlFor="email" className="block text-xs font-bold text-slate-300 uppercase tracking-widest mb-2 group-focus-within:text-emerald-400 transition-colors">Email Address</label>
          <input 
            id="email"
            type="email" 
            name="email" 
            required 
            className="w-full px-5 py-4 bg-white/5 border border-white/10 rounded-2xl text-white text-lg focus:outline-none focus:border-emerald-400 focus:bg-white/10 transition-all shadow-inner"
            placeholder="you@example.com"
          />
          <ValidationError prefix="Email" field="email" errors={state.errors} className="text-red-400 text-xs mt-1" />
        </div>
        <div className="group">
          <label htmlFor="message" className="block text-xs font-bold text-slate-300 uppercase tracking-widest mb-2 group-focus-within:text-emerald-400 transition-colors">Message</label>
          <textarea 
            id="message"
            name="message" 
            required 
            rows="5" 
            className="w-full px-5 py-4 bg-white/5 border border-white/10 rounded-2xl text-white text-lg focus:outline-none focus:border-emerald-400 focus:bg-white/10 transition-all shadow-inner resize-none"
            placeholder="How can our environmental experts help?"
          ></textarea>
          <ValidationError prefix="Message" field="message" errors={state.errors} className="text-red-400 text-xs mt-1" />
        </div>
        <button type="submit" disabled={state.submitting} className="w-full py-4 mt-2 bg-gradient-to-r from-emerald-500 to-teal-400 hover:from-emerald-400 hover:to-teal-300 disabled:opacity-50 text-slate-900 text-lg font-black uppercase tracking-widest rounded-2xl transition-all shadow-[0_0_30px_-5px_rgba(16,185,129,0.5)] hover:shadow-[0_0_40px_-5px_rgba(16,185,129,0.7)] hover:scale-[1.02]">
          Initiate Contact
        </button>
      </form>
    </div>
  )
}

function App() {
  const [locations, setLocations] = useState([]);
  const [selectedRegion, setSelectedRegion] = useState('All');
  const [hash, setHash] = useState(window.location.hash || '#dashboard');

  useEffect(() => {
    const onHashChange = () => setHash(window.location.hash || '#dashboard');
    window.addEventListener('hashchange', onHashChange);
    
    // Hide the preloader when React finishes mounting
    const preloader = document.getElementById('preloader');
    if (preloader) {
      preloader.style.opacity = '0';
      setTimeout(() => {
        preloader.style.display = 'none';
      }, 500);
    }
    
    return () => window.removeEventListener('hashchange', onHashChange);
  }, []);

  useEffect(() => {
    fetch(`${API_BASE_URL}/api/locations`)
      .then(res => res.json())
      .then(data => setLocations(data))
      .catch(err => console.error("Error fetching locations data:", err));
  }, []);

  return (
    <div className="relative min-h-screen bg-slate-950 text-slate-100 font-sans overflow-hidden selection:bg-emerald-500 selection:text-slate-950">
      
      {/* Absolute Background Map */}
      <BackgroundMap locations={locations} selectedRegion={selectedRegion} />
      
      {/* Overlay UI Layer */}
      <div className="relative flex flex-col min-h-screen pointer-events-none">
        
        <Header locations={locations} selectedRegion={selectedRegion} onSelectRegion={setSelectedRegion} hash={hash} />
        
        <div className={`flex-1 overflow-y-auto pt-32 pb-12 ${hash === '#map' ? 'pointer-events-none' : 'pointer-events-auto'}`}>
          {hash === '#dashboard' && <MainContent selectedRegion={selectedRegion} locations={locations} />}
          {hash === '#map' && <MapOverlay locations={locations} />}
          {hash === '#tips' && <HealthTips selectedRegion={selectedRegion} />}
          {hash === '#privacy' && <PrivacyPolicy />}
          {hash === '#terms' && <TermsOfService />}
          {hash === '#contact' && <ContactExpert />}
        </div>
        
        <div className="pointer-events-auto mt-auto">
          <Footer />
        </div>
      </div>
    </div>
  )
}

export default App
